dgarana/vulcano

.gitignore, .travis.yml, MANIFEST.in, requirements/requirements.txt, requirements/test_requirements.txt, tox.ini, vulcano/app/classes.py, vulcano/app/test_classes.py, vulcano/core/classes.py, vulcano/core/test_classes.py
Create a vulcano app that can register commands into it in order to be
able to execute them after through command line or REPL.
Related feature: #1
=> Create Vulcano App

examples/simple_example.py, requirements/requirements.txt, requirements/test_requirements.txt, vulcano/app/classes.py, vulcano/app/test_classes.py, vulcano/command/builtin.py
Add REPL support by using prompt toolkit.
Add some examples of how to use it.
=> Enable REPL mode

vulcano/app/classes.py, vulcano/command/classes.py
Based on WordCompleter, add the first implementation just to list
commands and autocomplete them.
=> Add very basic completer

vulcano/app/classes.py
=> Implement fuzzy finder

vulcano/app/classes.py, vulcano/app/test_classes.py, vulcano/command/completer.py, vulcano/command/models.py, vulcano/command/test_completer.py
Instead of completing always with commands, support for completing the
command args has been added.
=> Add support for auto complete commands and args

examples/module_example.py, examples/my_module/my_funcs.py, vulcano/app/classes.py, vulcano/app/test_classes.py, vulcano/command/classes.py, vulcano/command/test_classes.py
This will help people that don't want to change their code.
Would be nice having printing results support before relasing this, as
they won't have the output if there's a return statement on their
functions.
=> Add register module option

vulcano/app/classes.py, vulcano/app/test_classes.py, vulcano/command/classes.py, vulcano/command/test_classes.py, vulcano/command/test_completer.py
Magma will be the name of the new CommandManager.
This closes issue #40
=> Rename CommandManager to Magma

examples/simple_example.py, vulcano/app/classes.py, vulcano/app/test_classes.py
=> Implement printing last result if enabled

vulcano/app/classes.py, vulcano/app/test_classes.py, vulcano/command/builtin.py
Manager should be public as we're using it from outside the app.
=> Promote manager to be public

vulcano/app/test_classes.py
Add some extra tests to execution handling from the command classes.
=> Increase coverage percentage

README.md, examples/simple_example.py, vulcano/app/classes.py, vulcano/app/test_classes.py
This is mainly for being able to create dinamycally commands that use
the context. This will help people to not having to implement accessing
the context inside their function, they just format it from the command
line.
=> Add support for formatting commands

README.md, examples/module_example.py, examples/simple_example.py, vulcano/app/classes.py, vulcano/app/lexer.py, vulcano/command/classes.py, vulcano/command/models.py
This will add printing source code with custom themes.
All custom themes are based on VulcanoStyle, which can transform
a pygments theme into a prompt_tookit style.
=> Implement printing source code with themes

setup.py, vulcano/app/classes.py, vulcano/app/lexer.py, vulcano/command/builtin.py, vulcano/vulcano_cli.py
Add pyparsing bigger or equal to 2.3.1 as a install requires, otherwise
it will get stuck while trying to parse command line.
=> Vulcano needs pyparsing 2.3.1

requirements/requirements.txt, vulcano/app/classes.py, vulcano/app/test_classes.py
=> Implement file history

vulcano/app/classes.py, vulcano/command/builtin.py, vulcano/command/classes.py, vulcano/command/models.py
This will help developers to avoid displaying some help about commands
that are not available yet or that you don't have suport.
=> Add support for hidding commands

vulcano/command/models.py
Add support for having also those default values for each argument, so
we can tell the user which value is given by default for each field.
This closes issue #50
=> Add default arguments

vulcano/app/classes.py
Add support for handling with suggestions, so in case the command to
execute do not exist, we look for the closer command to suggest it to
the user.
This closes feature #94
=> Add support for command suggestion

requirements/requirements.txt, setup.py, vulcano/command/models.py, vulcano/command/test_classes.py
Move some logic from vulcano to pynspector to keep them separated.
=> Implement pynspector for inspecting functions

vulcano/app/test_classes.py, vulcano/command/classes.py
Add missing tests for did_you_mean function.
=> Increase app.classes coverage

vulcano/command/test_builtin.py
Add more tests to improve builtin tests coverage.
=> Improve builtins tests coverage

vulcano/command/classes.py, vulcano/command/models.py, vulcano/command/models_test.py
Add new tests for command models and increase test covergae for models
module as well as implement boolean on show_if.
=> Increase test coverage for models
